/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.sun.glass.events.KeyEvent;
import controller.Controller;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author Luis
 */
public class AddManager extends javax.swing.JFrame {

    private Controller controller_;

    /**
     * Creates new form AddManagerFrame
     */
    public AddManager(Controller controller) {
        controller_ = controller;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        IdLabel = new javax.swing.JLabel();
        IdInputField = new javax.swing.JTextField();
        NameInputField = new javax.swing.JTextField();
        NameLabel = new javax.swing.JLabel();
        SalaryInputField = new javax.swing.JTextField();
        SalaryLabel = new javax.swing.JLabel();
        PhoneNumberInputField = new javax.swing.JTextField();
        PhoneNumberLabel = new javax.swing.JLabel();
        AddManagerButton = new javax.swing.JButton();
        MessageLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        PasswordInputField = new javax.swing.JPasswordField();
        CloseLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        IdLabel.setText("ID");

        IdInputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdInputFieldActionPerformed(evt);
            }
        });
        IdInputField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IdInputFieldKeyTyped(evt);
            }
        });

        NameInputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameInputFieldActionPerformed(evt);
            }
        });
        NameInputField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NameInputFieldKeyTyped(evt);
            }
        });

        NameLabel.setText("Nombre");

        SalaryInputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalaryInputFieldActionPerformed(evt);
            }
        });
        SalaryInputField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                SalaryInputFieldKeyTyped(evt);
            }
        });

        SalaryLabel.setText("Salario");

        PhoneNumberInputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneNumberInputFieldActionPerformed(evt);
            }
        });
        PhoneNumberInputField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PhoneNumberInputFieldKeyTyped(evt);
            }
        });

        PhoneNumberLabel.setText("Telefono");

        AddManagerButton.setText("Agregar");
        AddManagerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddManagerButtonActionPerformed(evt);
            }
        });

        PasswordLabel.setText("Contraseña");

        CloseLabel.setText("X");
        CloseLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IdInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NameLabel)
                            .addComponent(NameInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SalaryLabel)
                            .addComponent(SalaryInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PhoneNumberLabel)
                            .addComponent(AddManagerButton)
                            .addComponent(MessageLabel)
                            .addComponent(PasswordLabel)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(PasswordInputField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                .addComponent(PhoneNumberInputField, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addContainerGap(59, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(IdLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CloseLabel))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(IdLabel))
                    .addComponent(CloseLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IdInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NameInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SalaryLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SalaryInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PhoneNumberLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PhoneNumberInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PasswordLabel)
                .addGap(1, 1, 1)
                .addComponent(PasswordInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MessageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddManagerButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IdInputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdInputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdInputFieldActionPerformed

    private void NameInputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameInputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameInputFieldActionPerformed

    private void SalaryInputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalaryInputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalaryInputFieldActionPerformed

    private void PhoneNumberInputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneNumberInputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneNumberInputFieldActionPerformed

    private void AddManagerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddManagerButtonActionPerformed

        if(this.IdInputField.getText().isEmpty() || this.NameInputField.getText().isEmpty() || this.SalaryInputField.getText().isEmpty() || this.PhoneNumberInputField.getText().isEmpty() ||  new String(this.PasswordInputField.getPassword()).isEmpty()){
            JOptionPane.showMessageDialog(this, "Por favor ingrese todos los datos.");
            return;
        }

        String id = this.IdInputField.getText();
        String name = this.NameInputField.getText();
        float salary = Float.parseFloat(this.SalaryInputField.getText());
        String phoneNumber = this.PhoneNumberInputField.getText();
        String password = new String(this.PasswordInputField.getPassword());

        String message = controller_.createEmployee(id, name, "Gerente", salary, phoneNumber);
        message += controller_.createUser(id,password,"Gerente");

        JOptionPane.showMessageDialog(this, message, "Mensaje", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_AddManagerButtonActionPerformed

    private void CloseLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLabelMouseClicked
        this.dispose();
    }//GEN-LAST:event_CloseLabelMouseClicked

    private void IdInputFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IdInputFieldKeyTyped
        validateNumber(evt);
    }//GEN-LAST:event_IdInputFieldKeyTyped

    private void NameInputFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NameInputFieldKeyTyped
        validateCharacters(evt);
     }//GEN-LAST:event_NameInputFieldKeyTyped

    private void SalaryInputFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SalaryInputFieldKeyTyped
        validateNumber(evt);
    }//GEN-LAST:event_SalaryInputFieldKeyTyped

    private void PhoneNumberInputFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PhoneNumberInputFieldKeyTyped
        validateNumber(evt);
    }//GEN-LAST:event_PhoneNumberInputFieldKeyTyped
    
    //This function validates that all typed keys are numbers
    private void validateNumber(java.awt.event.KeyEvent evt) {
        char inputChar = evt.getKeyChar();
        if(!(Character.isDigit(inputChar))){
            evt.consume();
        }
    }
    
    //This function validates that all type kets are characters
    private void validateCharacters(java.awt.event.KeyEvent evt){
        char c = evt.getKeyChar();
        if (!Character.isLetter(c) && !Character.isWhitespace(c)) {
            evt.consume();
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddManagerButton;
    private javax.swing.JLabel CloseLabel;
    private javax.swing.JTextField IdInputField;
    private javax.swing.JLabel IdLabel;
    private javax.swing.JLabel MessageLabel;
    private javax.swing.JTextField NameInputField;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JPasswordField PasswordInputField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JTextField PhoneNumberInputField;
    private javax.swing.JLabel PhoneNumberLabel;
    private javax.swing.JTextField SalaryInputField;
    private javax.swing.JLabel SalaryLabel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
