/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import view.Employee.ManagerMenu;
import view.Employee.AdminMenu;
import view.Seller.SellerMenu;
import view.Foreman.ForemanMenu;
import javax.swing.JOptionPane;
import controller.Controller;
/**
 * 
 * @author jose
 */

public class Login extends javax.swing.JFrame {
    private Controller controller_;
    /**
     * Creates new form Login
     */
    public Login() {
        controller_ = new Controller();
        initComponents(); 
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        loginContainer = new keeptoo.KGradientPanel();
        userTextField = new javax.swing.JTextField();
        userLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        passwordLabel = new javax.swing.JLabel();
        loginButton = new keeptoo.KButton();
        jLabel1 = new javax.swing.JLabel();
        logoPanel = new keeptoo.KGradientPanel();
        separator = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(35, 39, 42));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginPanel.setBackground(new java.awt.Color(35, 39, 42));

        loginContainer.setkBorderRadius(30);
        loginContainer.setkEndColor(new java.awt.Color(44, 47, 51));
        loginContainer.setkStartColor(new java.awt.Color(44, 47, 51));
        loginContainer.setOpaque(false);

        userTextField.setBackground(new java.awt.Color(232, 233, 235));
        userTextField.setFont(new java.awt.Font("Laksaman", 0, 12)); // NOI18N
        userTextField.setForeground(new java.awt.Color(35, 39, 42));
        userTextField.setBorder(null);
        userTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTextFieldActionPerformed(evt);
            }
        });

        userLabel.setFont(new java.awt.Font("Laksaman", 1, 14)); // NOI18N
        userLabel.setForeground(new java.awt.Color(255, 255, 255));
        userLabel.setText("Usuario");

        passwordField.setBackground(new java.awt.Color(221, 220, 220));
        passwordField.setFont(new java.awt.Font("Laksaman", 0, 12)); // NOI18N
        passwordField.setForeground(new java.awt.Color(35, 39, 42));
        passwordField.setBorder(null);

        passwordLabel.setFont(new java.awt.Font("Laksaman", 1, 14)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordLabel.setText("Contraseña");

        loginButton.setBackground(new java.awt.Color(114, 137, 218));
        loginButton.setBorder(null);
        loginButton.setText("Iniciar Sesión");
        loginButton.setFont(new java.awt.Font("Laksaman", 1, 14)); // NOI18N
        loginButton.setkAllowGradient(false);
        loginButton.setkBackGroundColor(new java.awt.Color(114, 137, 218));
        loginButton.setkBorderRadius(30);
        loginButton.setkEndColor(new java.awt.Color(114, 137, 218));
        loginButton.setkHoverColor(new java.awt.Color(148, 169, 241));
        loginButton.setkHoverEndColor(new java.awt.Color(148, 169, 241));
        loginButton.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        loginButton.setkHoverStartColor(new java.awt.Color(148, 169, 241));
        loginButton.setkIndicatorColor(new java.awt.Color(114, 137, 218));
        loginButton.setkIndicatorThickness(0);
        loginButton.setkPressedColor(new java.awt.Color(75, 90, 144));
        loginButton.setkSelectedColor(new java.awt.Color(75, 90, 144));
        loginButton.setkStartColor(new java.awt.Color(114, 137, 218));
        loginButton.setOpaque(false);
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginContainerLayout = new javax.swing.GroupLayout(loginContainer);
        loginContainer.setLayout(loginContainerLayout);
        loginContainerLayout.setHorizontalGroup(
            loginContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginContainerLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(loginContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(userTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userLabel, javax.swing.GroupLayout.Alignment.LEADING)))
        );
        loginContainerLayout.setVerticalGroup(
            loginContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginContainerLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(passwordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/jose/Documents/avatar-inside-a-circle.png")); // NOI18N

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(loginContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(34, 34, 34))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loginContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        getContentPane().add(loginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 0, 439, 420));

        logoPanel.setkEndColor(new java.awt.Color(73, 88, 139));
        logoPanel.setkGradientFocus(100);
        logoPanel.setkStartColor(new java.awt.Color(114, 137, 218));
        logoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        separator.setBackground(new java.awt.Color(29, 32, 34));
        separator.setText(" ");
        separator.setOpaque(true);
        logoPanel.add(separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 10, 420));

        getContentPane().add(logoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTextFieldActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
                validateInput();

        String user = userTextField.getText();
        String password = new String(passwordField.getPassword());

        String message = controller_.login(user, password);

        if(message.contains("Error")){
            JOptionPane.showMessageDialog(this, message);
            return;
        }

        selectMenu(message);
    }//GEN-LAST:event_loginButtonActionPerformed

    private void selectMenu(String type){
        switch(type){
            case "Administrador":
                AdminMenu admin = new AdminMenu(controller_);
                admin.setTitle("Administrador - Menú Principal");
                admin.setLocationRelativeTo(null);
                admin.setVisible(true);
                this.dispose();
                break;
                
            case "Gerente":
                ManagerMenu manager = new ManagerMenu(controller_);
                manager.setTitle("Gerente - Menú Principal");
                manager.setLocationRelativeTo(null);
                manager.setVisible(true);
                this.dispose();
                break;
                
            case "Vendedor":
                SellerMenu seller = new SellerMenu(controller_);
                seller.setTitle("Vendendor - Menú Principal");
                seller.setLocationRelativeTo(null);
                seller.setVisible(true);
                this.dispose();
                break;
                
            case "Jefe de Taller":
                ForemanMenu foreman = new ForemanMenu(controller_);
                foreman.setTitle("Jefe de Taller - Menú Principal");
                foreman.setLocationRelativeTo(null);
                foreman.setVisible(true);
                this.dispose();
                break;
        }
    }
   
    private void validateInput(){
        if(userTextField.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Por favor ingrese un usuario");
            return;
        }
        if(passwordField.getPassword().length == 0){
            JOptionPane.showMessageDialog(this, "Por favor ingrese una contraseña");
            return;
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private keeptoo.KButton loginButton;
    private keeptoo.KGradientPanel loginContainer;
    private javax.swing.JPanel loginPanel;
    private keeptoo.KGradientPanel logoPanel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel separator;
    private javax.swing.JLabel userLabel;
    private javax.swing.JTextField userTextField;
    // End of variables declaration//GEN-END:variables
}
