/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;
import java.util.Map;
import javax.swing.JOptionPane;
import view.Foreman.ListCatalog;

/**
 *
 * @author Luis
 */
public class ModifyCommission extends javax.swing.JFrame {

    Controller controller_;

    /**
     * Creates new form ModifyCommission
     */
    public ModifyCommission(Controller controller) {
        controller_ = controller;
        initComponents();
        this.StatusComboBox.setEnabled(false);
        this.UpdateOrderButton.setEnabled(false);
        this.BranchTextField.setEditable(false);
        this.QuantityTextField.setEditable(false);
        this.FurnitureIdTextField.setEditable(false);
        this.StatusComboBox.setSelectedIndex(1);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InfoLoadPanel = new javax.swing.JPanel();
        OrderIdLabel = new javax.swing.JLabel();
        OrderIdTextField = new javax.swing.JTextField();
        LoadOrderInfoButton = new javax.swing.JButton();
        InfoUpdatePanel = new javax.swing.JPanel();
        StatusLabel = new javax.swing.JLabel();
        StatusComboBox = new javax.swing.JComboBox<>();
        UpdateOrderButton = new javax.swing.JButton();
        FurnitureIdLabel = new javax.swing.JLabel();
        QuantityLabel = new javax.swing.JLabel();
        BranchLabel = new javax.swing.JLabel();
        FurnitureIdTextField = new javax.swing.JTextField();
        QuantityTextField = new javax.swing.JTextField();
        BranchTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        InfoLoadPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        OrderIdLabel.setText("Numero de orden");

        OrderIdTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                OrderIdTextFieldKeyTyped(evt);
            }
        });

        LoadOrderInfoButton.setText("Cargar datos");
        LoadOrderInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadOrderInfoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InfoLoadPanelLayout = new javax.swing.GroupLayout(InfoLoadPanel);
        InfoLoadPanel.setLayout(InfoLoadPanelLayout);
        InfoLoadPanelLayout.setHorizontalGroup(
            InfoLoadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoLoadPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InfoLoadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OrderIdLabel)
                    .addComponent(LoadOrderInfoButton)
                    .addComponent(OrderIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        InfoLoadPanelLayout.setVerticalGroup(
            InfoLoadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoLoadPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(OrderIdLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OrderIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LoadOrderInfoButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        InfoUpdatePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        StatusLabel.setText("Estado");

        StatusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Terminado", "En proceso" }));

        UpdateOrderButton.setText("Actualizar");
        UpdateOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateOrderButtonActionPerformed(evt);
            }
        });

        FurnitureIdLabel.setText("Codigo mueble");

        QuantityLabel.setText("Cantidad");

        BranchLabel.setText("Sede");

        FurnitureIdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FurnitureIdTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InfoUpdatePanelLayout = new javax.swing.GroupLayout(InfoUpdatePanel);
        InfoUpdatePanel.setLayout(InfoUpdatePanelLayout);
        InfoUpdatePanelLayout.setHorizontalGroup(
            InfoUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoUpdatePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InfoUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BranchTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addGroup(InfoUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(QuantityTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(StatusLabel, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(StatusComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 121, Short.MAX_VALUE)
                        .addComponent(UpdateOrderButton, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(FurnitureIdLabel, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(QuantityLabel, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(BranchLabel, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(FurnitureIdTextField, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        InfoUpdatePanelLayout.setVerticalGroup(
            InfoUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InfoUpdatePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FurnitureIdLabel)
                .addGap(3, 3, 3)
                .addComponent(FurnitureIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(QuantityLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QuantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BranchLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BranchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StatusLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UpdateOrderButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InfoLoadPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(InfoUpdatePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InfoLoadPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InfoUpdatePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoadOrderInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadOrderInfoButtonActionPerformed
        if (OrderIdTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Error: ingrese el numero de orden sin modificar que desea modificar", "Atención", JOptionPane.INFORMATION_MESSAGE);
        } else {
            String order_id = OrderIdTextField.getText();
            Map<String, String> commissionInfo = controller_.getCommissionInfo(order_id);
            if (commissionInfo == null) {
                JOptionPane.showMessageDialog(this, "Error: el numero de orden sin terminar ingresado es incorrecto", "Error", JOptionPane.WARNING_MESSAGE);

            } else {
                this.StatusComboBox.setEnabled(true);
                this.UpdateOrderButton.setEnabled(true);
                this.LoadOrderInfoButton.setEnabled(false);
                this.OrderIdTextField.setEnabled(false);

                this.FurnitureIdTextField.setText(commissionInfo.get("furniture_id"));
                this.BranchTextField.setText(commissionInfo.get("branch"));
                this.QuantityTextField.setText(commissionInfo.get("quantity"));
                
               
            }
        }

    }//GEN-LAST:event_LoadOrderInfoButtonActionPerformed

    private void UpdateOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateOrderButtonActionPerformed
        String status = (String) this.StatusComboBox.getSelectedItem();
        String order_id = this.OrderIdTextField.getText();

        if (status.equals("Terminado")) {
            String mensaje = controller_.updateCommission(order_id, true);
            JOptionPane.showMessageDialog(this, mensaje, "Atención", JOptionPane.INFORMATION_MESSAGE);
            
            

            this.StatusComboBox.setEnabled(false);
            this.UpdateOrderButton.setEnabled(false);
            this.LoadOrderInfoButton.setEnabled(true);
            this.OrderIdTextField.setEnabled(true);
            this.BranchTextField.setText("");
            this.QuantityTextField.setText("");
            this.FurnitureIdTextField.setText("");
            

        } 
    }//GEN-LAST:event_UpdateOrderButtonActionPerformed

    private void OrderIdTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_OrderIdTextFieldKeyTyped
        validateNumber(evt);
    }//GEN-LAST:event_OrderIdTextFieldKeyTyped

    private void FurnitureIdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FurnitureIdTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FurnitureIdTextFieldActionPerformed

    //This function validates that all typed keys are numbers
    private void validateNumber(java.awt.event.KeyEvent evt) {
        char inputChar = evt.getKeyChar();
        if (!(Character.isDigit(inputChar))) {
            evt.consume();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListCatalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListCatalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListCatalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListCatalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifyCommission(new Controller()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BranchLabel;
    private javax.swing.JTextField BranchTextField;
    private javax.swing.JLabel FurnitureIdLabel;
    private javax.swing.JTextField FurnitureIdTextField;
    private javax.swing.JPanel InfoLoadPanel;
    private javax.swing.JPanel InfoUpdatePanel;
    private javax.swing.JButton LoadOrderInfoButton;
    private javax.swing.JLabel OrderIdLabel;
    private javax.swing.JTextField OrderIdTextField;
    private javax.swing.JLabel QuantityLabel;
    private javax.swing.JTextField QuantityTextField;
    private javax.swing.JComboBox<String> StatusComboBox;
    private javax.swing.JLabel StatusLabel;
    private javax.swing.JButton UpdateOrderButton;
    // End of variables declaration//GEN-END:variables
}
