/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;
import javax.swing.JOptionPane;
import java.util.HashMap;
/**
 *
 * @author lalil
 */
public class ModifyManager extends javax.swing.JFrame {
    private Controller controller_;
    private String userType_;
    /**
     * Creates new form ModifyManager
     */
    public ModifyManager(Controller controller,String userType) {
        controller_ = controller;
        userType_ = userType;
        
        initComponents();
        if(userType_.equals("Administrador")){
            this.ChargeComboBox.addItem("Gerente");
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IdLabel = new javax.swing.JLabel();
        IdInputField = new javax.swing.JTextField();
        ModifyButton = new javax.swing.JButton();
        NameLabel = new javax.swing.JLabel();
        ChargeLabel = new javax.swing.JLabel();
        SalaryLabel = new javax.swing.JLabel();
        PhoneNumberLabel = new javax.swing.JLabel();
        NameInputField = new javax.swing.JTextField();
        SalaryInputField = new javax.swing.JTextField();
        PhoneNumberInputField = new javax.swing.JTextField();
        UpdateButton = new javax.swing.JButton();
        ChargeComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        IdLabel.setText("Id:");

        IdInputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdInputFieldActionPerformed(evt);
            }
        });
        IdInputField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IdInputFieldKeyTyped(evt);
            }
        });

        ModifyButton.setText("Modificar");
        ModifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyButtonActionPerformed(evt);
            }
        });

        NameLabel.setText("Nombre:");

        ChargeLabel.setText("Cargo:");

        SalaryLabel.setText("Salario:");

        PhoneNumberLabel.setText("Telefono:");

        NameInputField.setEnabled(false);
        NameInputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameInputFieldActionPerformed(evt);
            }
        });
        NameInputField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NameInputFieldKeyTyped(evt);
            }
        });

        SalaryInputField.setEnabled(false);
        SalaryInputField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                SalaryInputFieldKeyTyped(evt);
            }
        });

        PhoneNumberInputField.setEnabled(false);
        PhoneNumberInputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneNumberInputFieldActionPerformed(evt);
            }
        });
        PhoneNumberInputField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PhoneNumberInputFieldKeyTyped(evt);
            }
        });

        UpdateButton.setText("Actualizar");
        UpdateButton.setEnabled(false);
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        ChargeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jefe de Taller", "Vendedor" }));
        ChargeComboBox.setEnabled(false);
        ChargeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChargeComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PhoneNumberLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PhoneNumberInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(SalaryLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                            .addComponent(SalaryInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(NameLabel)
                                .addComponent(ChargeLabel)
                                .addComponent(IdLabel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(NameInputField, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                .addComponent(IdInputField)
                                .addComponent(ChargeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(19, 19, 19)
                .addComponent(ModifyButton)
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(UpdateButton)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdLabel)
                    .addComponent(IdInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModifyButton))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLabel)
                    .addComponent(NameInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChargeLabel)
                    .addComponent(ChargeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SalaryLabel)
                    .addComponent(SalaryInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneNumberLabel)
                    .addComponent(PhoneNumberInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(UpdateButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void disable(){
        this.UpdateButton.setEnabled(false);
        this.NameInputField.setEnabled(false);
        this.ChargeComboBox.setEnabled(false);
        this.SalaryInputField.setEnabled(false);
        this.PhoneNumberInputField.setEnabled(false);
        this.NameInputField.setText("");
        this.SalaryInputField.setText("");
        this.PhoneNumberInputField.setText("");
        this.IdInputField.setText("");    
    }
    
    public void enable(){
        this.NameInputField.setEnabled(true);
        this.ChargeComboBox.setEnabled(true);
        this.SalaryInputField.setEnabled(true);
        this.PhoneNumberInputField.setEnabled(true);
        this.UpdateButton.setEnabled(true); 

    }
    
    private void ModifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyButtonActionPerformed
        // TODO add your handling code here:
        if(this.IdInputField.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Por favor insertar un ID");
            return;
        }
        String id = this.IdInputField.getText();
        
        HashMap <String, String>infoEmployee = controller_.getEmployeeInfo(id);
        
        
        if (infoEmployee.isEmpty()){
            JOptionPane.showMessageDialog(this,"No existe empleado con esa id");
            disable();
            return;
        }
        enable();
        this.NameInputField.setText(infoEmployee.get("name"));
        this.ChargeComboBox.setSelectedItem(infoEmployee.get("charge"));
        this.SalaryInputField.setText(infoEmployee.get("salary"));  
        this.PhoneNumberInputField.setText(infoEmployee.get("phoneNumber"));
        
        
    }//GEN-LAST:event_ModifyButtonActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
        String id = this.IdInputField.getText();
        String name = this.NameInputField.getText();
        String charge =  this.ChargeComboBox.getSelectedItem().toString();
        Float salary = Float.valueOf(this.SalaryInputField.getText());
        String phoneNumber = this.PhoneNumberInputField.getText();
        String message = controller_.updateEmployeeUser(id, name, charge, salary, phoneNumber, userType_);
        JOptionPane.showMessageDialog(this, message);
        disable();
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void IdInputFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IdInputFieldKeyTyped
        // TODO add your handling code here:
        char inputChar = evt.getKeyChar();
        if(!(Character.isDigit(inputChar))){
            evt.consume();
        }
    }//GEN-LAST:event_IdInputFieldKeyTyped

    private void SalaryInputFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SalaryInputFieldKeyTyped
        // TODO add your handling code here:
        char inputChar = evt.getKeyChar();
        if(!(Character.isDigit(inputChar))){
            evt.consume();
        }
    }//GEN-LAST:event_SalaryInputFieldKeyTyped

    private void NameInputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameInputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameInputFieldActionPerformed

    private void NameInputFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NameInputFieldKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isLetter(c) && !Character.isWhitespace(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_NameInputFieldKeyTyped

    private void PhoneNumberInputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneNumberInputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneNumberInputFieldActionPerformed

    private void PhoneNumberInputFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PhoneNumberInputFieldKeyTyped
        // TODO add your handling code here:
        char inputChar = evt.getKeyChar();
        if(!(Character.isDigit(inputChar))){
            evt.consume();
        }
    }//GEN-LAST:event_PhoneNumberInputFieldKeyTyped

    private void IdInputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdInputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdInputFieldActionPerformed

    private void ChargeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChargeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChargeComboBoxActionPerformed
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(createBranch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(createBranch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(createBranch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(createBranch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifyManager(new Controller(),"Administrador").setVisible(true);
            }
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ChargeComboBox;
    private javax.swing.JLabel ChargeLabel;
    private javax.swing.JTextField IdInputField;
    private javax.swing.JLabel IdLabel;
    private javax.swing.JButton ModifyButton;
    private javax.swing.JTextField NameInputField;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JTextField PhoneNumberInputField;
    private javax.swing.JLabel PhoneNumberLabel;
    private javax.swing.JTextField SalaryInputField;
    private javax.swing.JLabel SalaryLabel;
    private javax.swing.JButton UpdateButton;
    // End of variables declaration//GEN-END:variables
}
