/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.*;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author Granada
 */
public class ModifyBranch extends javax.swing.JFrame {

    private Controller controller_;

    /**
     * Creates new form ModifyBranch
     */
    public ModifyBranch(Controller controller) {
        controller_ = controller;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BranchNameLabel = new javax.swing.JLabel();
        BranchNameInputField = new javax.swing.JTextField();
        LoadBranchInfoButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        CityLabel = new javax.swing.JLabel();
        AddressLabel = new javax.swing.JLabel();
        OnChargeManagerIdLabel = new javax.swing.JLabel();
        UpdateButton = new javax.swing.JButton();
        addressTextField = new javax.swing.JTextField();
        CityInputField = new javax.swing.JTextField();
        OnChargeManagerInputField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        BranchNameLabel.setText("Nombre de la sede:");

        BranchNameInputField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BranchNameInputFieldKeyTyped(evt);
            }
        });

        LoadBranchInfoButton.setText("Cargar datos");
        LoadBranchInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadBranchInfoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BranchNameInputField)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LoadBranchInfoButton)
                            .addComponent(BranchNameLabel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BranchNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BranchNameInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LoadBranchInfoButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        CityLabel.setText("Ciudad:");

        AddressLabel.setText("Dirección:");

        OnChargeManagerIdLabel.setText("Id del gerente responsable:");

        UpdateButton.setText("Actualizar");
        UpdateButton.setEnabled(false);
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        addressTextField.setEnabled(false);

        CityInputField.setEnabled(false);
        CityInputField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CityInputFieldKeyTyped(evt);
            }
        });

        OnChargeManagerInputField.setEnabled(false);
        OnChargeManagerInputField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                OnChargeManagerInputFieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(CityLabel)
                        .addComponent(AddressLabel)
                        .addComponent(OnChargeManagerIdLabel)
                        .addComponent(addressTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                        .addComponent(CityInputField)
                        .addComponent(OnChargeManagerInputField))
                    .addComponent(UpdateButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CityLabel)
                .addGap(3, 3, 3)
                .addComponent(CityInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddressLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(OnChargeManagerIdLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OnChargeManagerInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UpdateButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enabled() {
        this.CityInputField.setEnabled(true);
        this.addressTextField.setEnabled(true);
        this.OnChargeManagerInputField.setEnabled(true);
        this.UpdateButton.setEnabled(true);

        //These components are disabled to prevent changes on the branch name once the branch info is loaded
        this.BranchNameInputField.setEnabled(false);
        this.LoadBranchInfoButton.setEnabled(false);
    }

    private void disabled() {
        this.CityInputField.setEnabled(false);
        this.CityInputField.setText("");
        this.addressTextField.setEnabled(false);
        this.addressTextField.setText("");
        this.OnChargeManagerInputField.setEnabled(false);
        this.OnChargeManagerInputField.setText("");
        this.UpdateButton.setEnabled(false);

        //These components are activated again once the update is succesful in order to make another operation
        this.BranchNameInputField.setEnabled(true);
        this.LoadBranchInfoButton.setEnabled(true);
    }

    private void LoadBranchInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadBranchInfoButtonActionPerformed
        // TODO add your handling code here:
        if (this.BranchNameInputField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor insertar un nombre de sede", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;

        } else {

            String branchName = this.BranchNameInputField.getText();

            HashMap<String, String> branchInfo = new HashMap<>();

            branchInfo = controller_.getBranchInfo(branchName);

            if (branchInfo.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No existe una sede con ese nombre");
                disabled();
                return;
            }

            enabled();
            this.CityInputField.setText(branchInfo.get("city"));
            this.addressTextField.setText(branchInfo.get("address"));
            this.OnChargeManagerInputField.setText(branchInfo.get("managerId"));
        }
    }//GEN-LAST:event_LoadBranchInfoButtonActionPerformed

    private void CityInputFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CityInputFieldKeyTyped
        validateCharacters(evt);
    }//GEN-LAST:event_CityInputFieldKeyTyped

    private void OnChargeManagerInputFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_OnChargeManagerInputFieldKeyTyped
        validateNumbers(evt);
    }//GEN-LAST:event_OnChargeManagerInputFieldKeyTyped

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
        String name = this.BranchNameInputField.getText();
        String city = this.CityInputField.getText();
        String address = this.addressTextField.getText();
        String managerId = this.OnChargeManagerInputField.getText();

        String message = controller_.updateBranch(name, city, address, managerId);

        JOptionPane.showMessageDialog(this, message);

        disabled();
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void BranchNameInputFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BranchNameInputFieldKeyTyped
        validateCharacters(evt);
    }//GEN-LAST:event_BranchNameInputFieldKeyTyped

    private void validateNumbers(java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }

    private void validateCharacters(java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar();
        if ((!Character.isLetter(c)) && (!Character.isWhitespace(c))) {
            evt.consume();
        }
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressLabel;
    private javax.swing.JTextField BranchNameInputField;
    private javax.swing.JLabel BranchNameLabel;
    private javax.swing.JTextField CityInputField;
    private javax.swing.JLabel CityLabel;
    private javax.swing.JButton LoadBranchInfoButton;
    private javax.swing.JLabel OnChargeManagerIdLabel;
    private javax.swing.JTextField OnChargeManagerInputField;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
