/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Branch;

import controller.Controller;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jaime
 */
public class ListBranches extends javax.swing.JFrame {

    private Controller controller_;
    /**
     * Creates new form ListBranches
     */
    public ListBranches(Controller controller) {
        controller_ = controller;
        initComponents();
        buttonGroupBranches.add(activeRadioButton);
        buttonGroupBranches.add(inactiveRadioButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupBranches = new javax.swing.ButtonGroup();
        activeRadioButton = new javax.swing.JRadioButton();
        inactiveRadioButton = new javax.swing.JRadioButton();
        dataScrollPane = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        searchLabel = new javax.swing.JLabel();
        exitLabel = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        activeRadioButton.setSelected(true);
        getContentPane().add(activeRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, -1, -1));
        getContentPane().add(inactiveRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, -1, -1));

        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Ciudad", "Dirección"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dataTable.setEnabled(false);
        dataScrollPane.setViewportView(dataTable);
        if (dataTable.getColumnModel().getColumnCount() > 0) {
            dataTable.getColumnModel().getColumn(0).setResizable(false);
            dataTable.getColumnModel().getColumn(2).setResizable(false);
        }

        getContentPane().add(dataScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 760, 250));

        searchLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchLabelMouseClicked(evt);
            }
        });
        getContentPane().add(searchLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 170, 320, 50));

        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabelMouseClicked(evt);
            }
        });
        getContentPane().add(exitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(761, 0, 80, 40));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_resources/List Branches.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchLabelMouseClicked
        List<Map<String, String>> results = new ArrayList<>();
        if(activeRadioButton.isSelected()){
            results = controller_.tableBranches(true);
        }
        else{
            results = controller_.tableBranches(false);
        }
        
        Object[] columnNames = { "Nombre", "Ciudad", "Dirección"};
        DefaultTableModel model = new DefaultTableModel(columnNames,0);
        
        if(results.isEmpty()) {
            dataTable.setModel(model);
            JOptionPane.showMessageDialog(null, "No se encontraron resultados", "Sedes", JOptionPane.INFORMATION_MESSAGE);            
            return;
        }        
        
        for(int i=0; i<results.size(); i++) {
            Object[] row = {
                results.get(i).get("name"),
                results.get(i).get("city"),
                results.get(i).get("address")
            };
            model.addRow(row);
        }
        dataTable.setModel(model);
    }//GEN-LAST:event_searchLabelMouseClicked

    private void exitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseClicked
        this.dispose();
    }//GEN-LAST:event_exitLabelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton activeRadioButton;
    private javax.swing.JLabel background;
    private javax.swing.ButtonGroup buttonGroupBranches;
    private javax.swing.JScrollPane dataScrollPane;
    private javax.swing.JTable dataTable;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JRadioButton inactiveRadioButton;
    private javax.swing.JLabel searchLabel;
    // End of variables declaration//GEN-END:variables
}
