/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Branch;

import controller.*;
import javax.swing.JOptionPane;
import java.util.Map;

/**
 *
 * @author Granada
 */
public class ModifyBranch extends javax.swing.JFrame {

    private Controller controller_;

    /**
     * Creates new form ModifyBranch
     */
    public ModifyBranch(Controller controller) {
        controller_ = controller;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        branchNameInputField = new javax.swing.JTextField();
        cityInputField = new javax.swing.JTextField();
        addressTextField = new javax.swing.JTextField();
        loadLabel = new javax.swing.JLabel();
        exitLabel = new javax.swing.JLabel();
        okLabel = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        branchNameInputField.setBackground(new java.awt.Color(255, 255, 255, 0));
        branchNameInputField.setForeground(new java.awt.Color(0, 0, 0));
        branchNameInputField.setBorder(null);
        branchNameInputField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                branchNameInputFieldKeyTyped(evt);
            }
        });
        getContentPane().add(branchNameInputField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 190, 30));

        cityInputField.setBackground(new java.awt.Color(255, 255, 255, 0));
        cityInputField.setForeground(new java.awt.Color(255, 255, 255));
        cityInputField.setBorder(null);
        cityInputField.setEnabled(false);
        cityInputField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cityInputFieldKeyTyped(evt);
            }
        });
        getContentPane().add(cityInputField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 173, 250, 30));

        addressTextField.setBackground(new java.awt.Color(255, 255, 255, 0));
        addressTextField.setForeground(new java.awt.Color(255, 255, 255));
        addressTextField.setBorder(null);
        addressTextField.setEnabled(false);
        getContentPane().add(addressTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 250, 30));

        loadLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loadLabelMouseClicked(evt);
            }
        });
        getContentPane().add(loadLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 60, 30));

        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabelMouseClicked(evt);
            }
        });
        getContentPane().add(exitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 0, 50, 40));

        okLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okLabelMouseClicked(evt);
            }
        });
        getContentPane().add(okLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 320, 200, 40));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_resources/Modify Branch.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enabled() {
        cityInputField.setEnabled(true);
        addressTextField.setEnabled(true);
        okLabel.setEnabled(true);

        //These components are disabled to prevent changes on the branch name once the branch info is loaded
        branchNameInputField.setEnabled(false);
        loadLabel.setEnabled(false);
    }

    private void disabled() {
        cityInputField.setEnabled(false);
        cityInputField.setText("");
        addressTextField.setEnabled(false);
        addressTextField.setText("");
        okLabel.setEnabled(false);

        //These components are activated again once the update is succesful in order to make another operation
        branchNameInputField.setEnabled(true);
        loadLabel.setEnabled(true);
    }

    private void cityInputFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cityInputFieldKeyTyped
        validateCharacters(evt);
    }//GEN-LAST:event_cityInputFieldKeyTyped

    private void branchNameInputFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_branchNameInputFieldKeyTyped
        validateCharactersAndNumbers(evt);
    }//GEN-LAST:event_branchNameInputFieldKeyTyped

    private void loadLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loadLabelMouseClicked
        if (branchNameInputField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor insertar un nombre de sede", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;

        }

        String branchName = branchNameInputField.getText();

        Map<String, String> branchInfo = controller_.getBranchInfo(branchName);

        if (branchInfo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No existe una sede con ese nombre");
            disabled();
            return;
        }

        enabled();
        cityInputField.setText(branchInfo.get("city"));
        addressTextField.setText(branchInfo.get("address"));
    }//GEN-LAST:event_loadLabelMouseClicked

    private void okLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okLabelMouseClicked
        if ( this.cityInputField.getText().trim().isEmpty() || this.addressTextField.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Error: asegurese de llenar todos los campos", "Alerta", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String name = this.branchNameInputField.getText();
        String city = this.cityInputField.getText();
        String address = this.addressTextField.getText();

        String message = controller_.updateBranch(name, city, address);

        JOptionPane.showMessageDialog(this, message);
        
        clearFields();
        disabled();
        
    }//GEN-LAST:event_okLabelMouseClicked

    private void exitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseClicked
        this.dispose();
    }//GEN-LAST:event_exitLabelMouseClicked

    private void validateCharacters(java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar();
        if ((!Character.isLetter(c)) && (!Character.isWhitespace(c))) {
            evt.consume();
        }
    }
    
    private void validateCharactersAndNumbers(java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar();
        if ((!Character.isLetter(c)) && (!Character.isDigit(c)) && (!Character.isWhitespace(c))) {
            evt.consume();
        }
    }
    
    private void clearFields(){
        this.addressTextField.setText("");
        this.branchNameInputField.setText("");
        this.cityInputField.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressTextField;
    private javax.swing.JLabel background;
    private javax.swing.JTextField branchNameInputField;
    private javax.swing.JTextField cityInputField;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JLabel loadLabel;
    private javax.swing.JLabel okLabel;
    // End of variables declaration//GEN-END:variables
}
