/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Employee;

import controller.Controller;
import java.time.LocalDate;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingWorker;
import org.knowm.xchart.CategoryChart;
import org.knowm.xchart.CategoryChartBuilder;
import org.knowm.xchart.SwingWrapper;
import org.knowm.xchart.XChartPanel;
import org.knowm.xchart.style.Styler;

/**
 *
 * @author Luis
 */
public class FurnitureReport extends javax.swing.JFrame {

    Controller controller_;

    /**
     * Creates new form SalesVsBranchReport
     */
    public FurnitureReport(Controller controller) {
        controller_ = controller;
        initComponents();
        List<String> branches = controller.listBranches();
        for(String branch: branches){
            this.branchComboBox.addItem(branch);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DatesPanel = new javax.swing.JPanel();
        InitialDatePicker = new com.github.lgooddatepicker.components.DatePicker();
        InitialDateLabel = new javax.swing.JLabel();
        EndDatePicker = new com.github.lgooddatepicker.components.DatePicker();
        EndDateLabel = new javax.swing.JLabel();
        ShowReportButton = new javax.swing.JButton();
        branchLabel = new javax.swing.JLabel();
        branchComboBox = new javax.swing.JComboBox<>();
        ChartPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DatesPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        InitialDateLabel.setText("Fecha inicial");

        EndDateLabel.setText("Fecha final");

        ShowReportButton.setText("Mostrar reporte");
        ShowReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowReportButtonActionPerformed(evt);
            }
        });

        branchLabel.setText("Sede");

        branchComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas las sedes" }));

        javax.swing.GroupLayout DatesPanelLayout = new javax.swing.GroupLayout(DatesPanel);
        DatesPanel.setLayout(DatesPanelLayout);
        DatesPanelLayout.setHorizontalGroup(
            DatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InitialDateLabel)
                    .addComponent(InitialDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EndDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EndDateLabel))
                .addGap(26, 26, 26)
                .addGroup(DatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(branchComboBox, 0, 106, Short.MAX_VALUE)
                    .addGroup(DatesPanelLayout.createSequentialGroup()
                        .addComponent(branchLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(ShowReportButton)
                .addGap(83, 83, 83))
        );
        DatesPanelLayout.setVerticalGroup(
            DatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatesPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(DatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DatesPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(branchComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(ShowReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(DatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DatesPanelLayout.createSequentialGroup()
                                .addComponent(InitialDateLabel)
                                .addGap(6, 6, 6)
                                .addComponent(InitialDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(DatesPanelLayout.createSequentialGroup()
                                .addGroup(DatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(EndDateLabel)
                                    .addComponent(branchLabel))
                                .addGap(6, 6, 6)
                                .addComponent(EndDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        ChartPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        ChartPanel.setLayout(new javax.swing.BoxLayout(ChartPanel, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ChartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DatesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DatesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ChartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ShowReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowReportButtonActionPerformed
        LocalDate initialDate = this.InitialDatePicker.getDate();
        LocalDate endDate = this.EndDatePicker.getDate();
        if (initialDate == null || endDate == null) {
            JOptionPane.showMessageDialog(this, "Error: debe seleccionar el rango de fechas a buscar", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } 
            
        List<Map<String, String>> data = controller_.getFurnitureSalesInfo(initialDate, endDate, (String) this.branchComboBox.getSelectedItem());
        CategoryChart chart = new CategoryChartBuilder().width(800).height(600).title("Muebles vs. Ventas").xAxisTitle("Muebles").yAxisTitle("Cantidad de ventas").theme(Styler.ChartTheme.GGPlot2).build();

        if(data.isEmpty()){
            JOptionPane.showMessageDialog(this, "No hubu ninguna venta en las fechas dadas", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        for(Map<String, String> furniture: data){
            chart.addSeries(furniture.get("id_name_furniture"), 
                    Arrays.asList(new String[] {(String)this.branchComboBox.getSelectedItem()}), 
                    Arrays.asList(new Number[] {Integer.valueOf(furniture.get("total_quantity"))}));
        }
        JPanel chartPanelArea = new XChartPanel(chart);
        ChartPanel.removeAll();
        ChartPanel.revalidate();
        ChartPanel.repaint();
        ChartPanel.add(chartPanelArea);
        ChartPanel.validate();
        
    }//GEN-LAST:event_ShowReportButtonActionPerformed

    private CategoryChart getChart(Map<String, List> data) {
        List<String> branches = data.get("branches");
        List<Integer> values = data.get("values");

        CategoryChart chart = new CategoryChartBuilder().width(400).height(600).title("Total ventas por sede").xAxisTitle("Sedes").yAxisTitle("Ventas").build();

        chart.addSeries("Ventas", branches, values);
        chart.getStyler().setHasAnnotations(true);

        return chart;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ChartPanel;
    private javax.swing.JPanel DatesPanel;
    private javax.swing.JLabel EndDateLabel;
    private com.github.lgooddatepicker.components.DatePicker EndDatePicker;
    private javax.swing.JLabel InitialDateLabel;
    private com.github.lgooddatepicker.components.DatePicker InitialDatePicker;
    private javax.swing.JButton ShowReportButton;
    private javax.swing.JComboBox<String> branchComboBox;
    private javax.swing.JLabel branchLabel;
    // End of variables declaration//GEN-END:variables

    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FurnitureReport(new Controller()).setVisible(true);
            }
        });
    }
}
