/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Employee;

import controller.Controller;
import javax.swing.JOptionPane;
import java.util.Map;
/**
 *
 * @author lalil
 */
public class ModifyEmployee extends javax.swing.JFrame {
    private Controller controller_;
    private String userType_;
    /**
     * Creates new form ModifyManager
     */
    public ModifyEmployee(Controller controller,String userType) {
        controller_ = controller;
        userType_ = userType;
        
        initComponents();
        if(userType_.equals("Administrador")){
            chargeCombo.addItem("Gerente");
        }
        chargeCombo.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        idTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        salaryTextField = new javax.swing.JTextField();
        phoneNumberTextField = new javax.swing.JTextField();
        chargeCombo = new javax.swing.JComboBox<>();
        branchTextField = new javax.swing.JTextField();
        modifyButton = new javax.swing.JLabel();
        searchButton = new javax.swing.JLabel();
        exitButton = new javax.swing.JLabel();
        UI = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        idTextField.setBackground(new java.awt.Color(255, 255, 255, 0));
        idTextField.setBorder(null);
        idTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextFieldActionPerformed(evt);
            }
        });
        idTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idTextFieldKeyTyped(evt);
            }
        });
        jPanel1.add(idTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 103, 190, 30));

        nameTextField.setBackground(new java.awt.Color(255, 255, 255, 0));
        nameTextField.setBorder(null);
        nameTextField.setEnabled(false);
        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });
        nameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameTextFieldKeyTyped(evt);
            }
        });
        jPanel1.add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 240, 30));

        salaryTextField.setBackground(new java.awt.Color(255, 255, 255, 0));
        salaryTextField.setBorder(null);
        salaryTextField.setEnabled(false);
        salaryTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                salaryTextFieldKeyTyped(evt);
            }
        });
        jPanel1.add(salaryTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 325, 80, 20));

        phoneNumberTextField.setBackground(new java.awt.Color(255, 255, 255, 0));
        phoneNumberTextField.setBorder(null);
        phoneNumberTextField.setEnabled(false);
        phoneNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumberTextFieldActionPerformed(evt);
            }
        });
        phoneNumberTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phoneNumberTextFieldKeyTyped(evt);
            }
        });
        jPanel1.add(phoneNumberTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 230, 20));

        chargeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Gerente", "Jefe de Taller", "Vendedor" }));
        chargeCombo.setEnabled(false);
        chargeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chargeComboActionPerformed(evt);
            }
        });
        jPanel1.add(chargeCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 255, 250, 30));

        branchTextField.setBackground(new java.awt.Color(255, 255, 255, 0));
        branchTextField.setBorder(null);
        branchTextField.setEnabled(false);
        branchTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                branchTextFieldKeyTyped(evt);
            }
        });
        jPanel1.add(branchTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 325, 123, 20));

        modifyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modifyButtonMouseClicked(evt);
            }
        });
        jPanel1.add(modifyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 480, 200, 40));

        searchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchButtonMouseClicked(evt);
            }
        });
        jPanel1.add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 95, 60, 40));

        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitButtonMouseClicked(evt);
            }
        });
        jPanel1.add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 50, 40));

        UI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_resources/Modify Employee Menu.png"))); // NOI18N
        UI.setText("jLabel1");
        jPanel1.add(UI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 540));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void disable(){
        modifyButton.setEnabled(false);
        idTextField.setEnabled(false);
        chargeCombo.setEnabled(false);
        salaryTextField.setEnabled(false);
        phoneNumberTextField.setEnabled(false);
        branchTextField.setEnabled(false);
        nameTextField.setText("");
        salaryTextField.setText("");
        phoneNumberTextField.setText("");
        branchTextField.setText("");
        idTextField.setText("");
        idTextField.setEnabled(true);
        searchButton.setEnabled(true);
    }
    
    public void enable(){
        nameTextField.setEnabled(true);
        chargeCombo.setEnabled(true);
        salaryTextField.setEnabled(true);
        phoneNumberTextField.setEnabled(true);
        modifyButton.setEnabled(true);
        branchTextField.setEnabled(true);
        idTextField.setEnabled(false);
        searchButton.setEnabled(false);
    }
    
    private void idTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idTextFieldKeyTyped
        // TODO add your handling code here:
        char inputChar = evt.getKeyChar();
        if(!(Character.isDigit(inputChar))){
            evt.consume();
        }
    }//GEN-LAST:event_idTextFieldKeyTyped

    private void salaryTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salaryTextFieldKeyTyped
        // TODO add your handling code here:
        char inputChar = evt.getKeyChar();
        if(!(Character.isDigit(inputChar))){
            evt.consume();
        }
    }//GEN-LAST:event_salaryTextFieldKeyTyped

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void nameTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTextFieldKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isLetter(c) && !Character.isWhitespace(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_nameTextFieldKeyTyped

    private void phoneNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumberTextFieldActionPerformed

    private void phoneNumberTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneNumberTextFieldKeyTyped
        // TODO add your handling code here:
        char inputChar = evt.getKeyChar();
        if(!(Character.isDigit(inputChar))){
            evt.consume();
        }
    }//GEN-LAST:event_phoneNumberTextFieldKeyTyped

    private void idTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTextFieldActionPerformed

    private void chargeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chargeComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chargeComboActionPerformed

    private void branchTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_branchTextFieldKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isLetter(c) && !Character.isWhitespace(c) && !Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_branchTextFieldKeyTyped

    private void modifyButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyButtonMouseClicked
        String id = idTextField.getText();
        String name = nameTextField.getText();
        String branch = branchTextField.getText();
        String charge =  chargeCombo.getSelectedItem().toString();
        Float salary = Float.valueOf(salaryTextField.getText());
        String phoneNumber = phoneNumberTextField.getText();
        String message = controller_.updateEmployee(id, name, branch, charge, salary, phoneNumber, userType_);
        JOptionPane.showMessageDialog(this, message);
        disable();
        idTextField.setEditable(true);
        clearFields();
    }//GEN-LAST:event_modifyButtonMouseClicked

    private void searchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseClicked
        if(idTextField.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Por favor insertar un ID");
            return;
        }
        String id = idTextField.getText();
        
        Map <String, String>infoEmployee = controller_.getEmployeeInfo(id);
        
        
        if (infoEmployee.isEmpty()){
            JOptionPane.showMessageDialog(this,"No existe empleado con esa id");
            disable();
            return;
        }
        enable();
        idTextField.setEditable(false);
        nameTextField.setText(infoEmployee.get("name"));
        chargeCombo.setSelectedItem(infoEmployee.get("charge"));
        salaryTextField.setText(infoEmployee.get("salary"));  
        phoneNumberTextField.setText(infoEmployee.get("phoneNumber"));
        branchTextField.setText(infoEmployee.get("branch"));
    }//GEN-LAST:event_searchButtonMouseClicked

    private void exitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseClicked
        this.dispose();
    }//GEN-LAST:event_exitButtonMouseClicked

    private void clearFields(){
        this.idTextField.setText("");
        this.nameTextField.setText("");
        this.branchTextField.setText("");
        this.phoneNumberTextField.setText("");
        this.salaryTextField.setText("");
        this.chargeCombo.setSelectedIndex(0);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel UI;
    private javax.swing.JTextField branchTextField;
    private javax.swing.JComboBox<String> chargeCombo;
    private javax.swing.JLabel exitButton;
    private javax.swing.JTextField idTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel modifyButton;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField phoneNumberTextField;
    private javax.swing.JTextField salaryTextField;
    private javax.swing.JLabel searchButton;
    // End of variables declaration//GEN-END:variables
}
