/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Foreman;

import controller.Controller;
import javax.swing.JOptionPane;
/**
 *
 * @author mily
 */
public class DeleteFurniture extends javax.swing.JFrame {
    private Controller controller_;
    /**
     * Creates new form DeleteFurniture
     */
    public DeleteFurniture(Controller controller) {
        controller_ = controller;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idTextField = new javax.swing.JTextField();
        deleteLabel = new javax.swing.JLabel();
        exitLabel = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        idTextField.setBackground(new java.awt.Color(255, 255, 255, 0));
        idTextField.setForeground(new java.awt.Color(255, 255, 255));
        idTextField.setBorder(null);
        idTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idTextFieldKeyTyped(evt);
            }
        });
        getContentPane().add(idTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 230, 30));

        deleteLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteLabelMouseClicked(evt);
            }
        });
        getContentPane().add(deleteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 200, 30));

        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabelMouseClicked(evt);
            }
        });
        getContentPane().add(exitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 50, 40));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_resources/Delete Furniture.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idTextFieldKeyTyped
        // TODO add your handling code here:
        validateNumber(evt);
    }//GEN-LAST:event_idTextFieldKeyTyped

    private void deleteLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteLabelMouseClicked
        if (this.idTextField.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Por favor insertar un ID");
            return;
        }
        
        int id = Integer.parseInt(this.idTextField.getText());
        String message = this.controller_.deleteFurniture(id);
        
        JOptionPane.showMessageDialog(this, message);
        clearFields();        
    }//GEN-LAST:event_deleteLabelMouseClicked

    private void exitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseClicked
       this.dispose();
    }//GEN-LAST:event_exitLabelMouseClicked

    public void validateNumber(java.awt.event.KeyEvent evt){
        char inputChar = evt.getKeyChar();
        if(!(Character.isDigit(inputChar))){
            evt.consume();
        }      
    }

    private void clearFields(){
        this.idTextField.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel deleteLabel;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JTextField idTextField;
    // End of variables declaration//GEN-END:variables
}
