/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Foreman;

import controller.Controller;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author sofia
 */
public class ModifyFurniture extends javax.swing.JFrame {
    private Controller controller_;
    /**
     * Creates new form ModifyFurniture
     */
    public ModifyFurniture(Controller controller) {
        controller_ = controller;
        initComponents();
        this.disable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void disable(){
        modifyLabel.setEnabled(false);
        nameTextField.setEnabled(false);
        colorTextField.setEnabled(false);
        weightTextField.setEnabled(false);
        priceTextField.setEnabled(false);
        materialTextField.setEnabled(false);
        idTextField.setEnabled(true);
        loadLabel.setEnabled(true);
        idTextField.setText("");
        nameTextField.setText("");
        colorTextField.setText("");
        weightTextField.setText("");
        priceTextField.setText("");
        idTextField.setText("");  
        materialTextField.setText("");
    }
    
    public void enable(){
        modifyLabel.setEnabled(true);
        nameTextField.setEnabled(true);
        colorTextField.setEnabled(true);
        weightTextField.setEnabled(true);
        priceTextField.setEnabled(true);
        materialTextField.setEnabled(true);
        idTextField.setEnabled(false);
        loadLabel.setEnabled(false);
    }
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        priceTextField = new javax.swing.JTextField();
        materialTextField = new javax.swing.JTextField();
        weightTextField = new javax.swing.JTextField();
        colorTextField = new javax.swing.JTextField();
        modifyLabel = new javax.swing.JLabel();
        exitLabel = new javax.swing.JLabel();
        loadLabel = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        idTextField.setBackground(new java.awt.Color(255, 255, 255, 0));
        idTextField.setForeground(new java.awt.Color(0, 0, 0));
        idTextField.setBorder(null);
        idTextField.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                idTextFieldCaretPositionChanged(evt);
            }
        });
        idTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextFieldActionPerformed(evt);
            }
        });
        idTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idTextFieldKeyTyped(evt);
            }
        });
        getContentPane().add(idTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 180, 40));

        nameTextField.setBackground(new java.awt.Color(255, 255, 255, 0));
        nameTextField.setForeground(new java.awt.Color(255, 255, 255));
        nameTextField.setBorder(null);
        getContentPane().add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 240, 30));

        priceTextField.setBackground(new java.awt.Color(255, 255, 255, 0));
        priceTextField.setForeground(new java.awt.Color(255, 255, 255));
        priceTextField.setBorder(null);
        priceTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                priceTextFieldKeyTyped(evt);
            }
        });
        getContentPane().add(priceTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 240, 30));

        materialTextField.setBackground(new java.awt.Color(255, 255, 255, 0));
        materialTextField.setForeground(new java.awt.Color(255, 255, 255));
        materialTextField.setBorder(null);
        getContentPane().add(materialTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 240, 30));

        weightTextField.setBackground(new java.awt.Color(255, 255, 255, 0));
        weightTextField.setForeground(new java.awt.Color(255, 255, 255));
        weightTextField.setBorder(null);
        weightTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                weightTextFieldKeyTyped(evt);
            }
        });
        getContentPane().add(weightTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 240, 30));

        colorTextField.setBackground(new java.awt.Color(255, 255, 255, 0));
        colorTextField.setForeground(new java.awt.Color(255, 255, 255));
        colorTextField.setBorder(null);
        getContentPane().add(colorTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 240, 30));

        modifyLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modifyLabelMouseClicked(evt);
            }
        });
        getContentPane().add(modifyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 520, 200, 50));

        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabelMouseClicked(evt);
            }
        });
        getContentPane().add(exitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 50, 40));

        loadLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loadLabelMouseClicked(evt);
            }
        });
        getContentPane().add(loadLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 60, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_resources/Modify Furniture.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTextFieldActionPerformed
    
    private void idTextFieldCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_idTextFieldCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_idTextFieldCaretPositionChanged

    private void idTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idTextFieldKeyTyped
        char inputChar = evt.getKeyChar();
        if(!(Character.isDigit(inputChar))){
            evt.consume();
        }
    }//GEN-LAST:event_idTextFieldKeyTyped

    private void priceTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priceTextFieldKeyTyped
        char inputChar = evt.getKeyChar();
        if(!(Character.isDigit(inputChar))) {
            evt.consume();
        }
    }//GEN-LAST:event_priceTextFieldKeyTyped

    private void weightTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_weightTextFieldKeyTyped
        char inputChar = evt.getKeyChar();
        if(!(Character.isDigit(inputChar))  && (inputChar != '.')) {
            evt.consume();
        }
    }//GEN-LAST:event_weightTextFieldKeyTyped

    private void loadLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loadLabelMouseClicked
        if(idTextField.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Por favor insertar un ID");
            return;
        }
        int id = Integer.parseInt(idTextField.getText());
        
        Map <String, String>infoFurniture = controller_.getActiveFurnitureInfo(id);
        
        if (infoFurniture.isEmpty()){
            JOptionPane.showMessageDialog(this,"No existe un mueble con esa id");  
            idTextField.setText("");
            return;
        }
        
        enable();
        
        nameTextField.setText(infoFurniture.get("name"));
        priceTextField.setText(infoFurniture.get("price"));  
        materialTextField.setText(infoFurniture.get("material"));
        weightTextField.setText(infoFurniture.get("weight"));
        colorTextField.setText(infoFurniture.get("color"));
    }//GEN-LAST:event_loadLabelMouseClicked

    private void modifyLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyLabelMouseClicked
      if(nameTextField.getText().trim().isEmpty() || colorTextField.getText().trim().isEmpty() || materialTextField.getText().trim().isEmpty() || priceTextField.getText().trim().isEmpty() || weightTextField.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(this, "Por favor ingrese todos los campos", "Atención", JOptionPane.WARNING_MESSAGE);
        return;
      }
        try {
            int id = Integer.parseInt(idTextField.getText());
            String name = nameTextField.getText();
            String color = colorTextField.getText();
            String material = materialTextField.getText();        
            Float price = Float.valueOf(priceTextField.getText());
            Float weight = Float.valueOf(weightTextField.getText());
            
            String message = controller_.updateFurniture(id, name, price, material, weight, color);
            JOptionPane.showMessageDialog(this, message);
            disable();            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Digite un valor numérico para el peso");              
        }  
    }//GEN-LAST:event_modifyLabelMouseClicked

    private void exitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitLabelMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JTextField colorTextField;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel loadLabel;
    private javax.swing.JTextField materialTextField;
    private javax.swing.JLabel modifyLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JTextField weightTextField;
    // End of variables declaration//GEN-END:variables
}
